### ISSUE TITLE
Week 1: Data collection, cleaning, and preprocessing.

### ISSUE THREAD

**Issue by GNAR1ZARD** [GNAR1ZARD/cryptoPriceAI#1]
- [x] Data Collection: Secure access to the cryptocurrency historical prices dataset, ensuring it contains all necessary features.
- [x] Data Inspection: Examine the dataset for missing values, outliers, or inconsistencies that could affect analysis.
- [x] Data Cleaning: Address any identified issues by removing, imputing, or correcting faulty data points.
- [x] Feature Selection: Determine which features are relevant to your prediction models and exclude irrelevant ones to streamline analysis.
- [x] Data Preprocessing: Normalize or standardize numerical data to ensure model compatibility and improve training efficiency. This step may also include encoding categorical variables if present.

**Comment by GNAR1ZARD** [comment]
- [x] Data Collection

https://www.kaggle.com/datasets/sudalairajkumar/cryptocurrency-historical-prices-coingecko

**Comment by GNAR1ZARD** [comment]
Data Inspection:

- [ ] Check for Missing Values
- [ ] Check for Outliers
- [ ] Check for Inconsistencies
- [ ] Check for Duplicate Entries
- [ ] Check Data Range

**Comment by dusek2** [comment]
- [x] There are no faulty data points. Cleaning done

Next step -> decide what features to pick.

**Comment by dusek2** [comment]
Feature: Volume, Market Cap, Date
